### ISSUE TITLE
Next meeting?

### ISSUE THREAD

**Issue by applemuncy** [City-of-Bloomington/civic-hacking#1]
I'm rather sure that April 25 was mentioned as the next meeting at the March 28th meeting. That would be today!

**Comment by charlesbrandt** [comment]
Thanks for the reminder and apologies for the delay... The next civic hacking group meeting will take place on May 16th at 5:30pm. We're finalizing the location and agenda, so we'll follow up.

**Comment by charlesbrandt** [comment]
The next meeting will be at 908 N Walnut Street on the 16th. Hope to see you then!
